name: Commit

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vagrant:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install vagrant
        run: |
          sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.15/vagrant_2.2.15_x86_64.deb
          sudo dpkg -i vagrant_2.2.15_x86_64.deb

      - name: Dump vagrant verson
        run: vagrant --version

      - name: Install libvirt
        run: sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-clients libvirt-dev qemu-kvm qemu-utils ruby-dev

      - name: Install vagrant-libvirt plugin
        run: sudo vagrant plugin install vagrant-libvirt

      - name: Start machines
        run: |
          sudo vagrant up --provider=libvirt
          sudo vagrant ssh -c "echo 'hello world!'"
          sudo ifconfig -a

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Add docker gpg key
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      - name: Add docker repository
        run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

      - name: Add bazel gpg key
        run: curl -fsSL https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

      - name: Add bazel repository
        run: echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

      - name: Install docker
        run: |
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Update our repository
        run: |
          ./tools/run_with_bazel.sh gazelle
          ./tools/run_with_bazel.sh update-repos

      - name: Reload our repository
        run: |
          ./tools/run_with_bazel.sh gazelle

      - name: Do selftest
        run: ./tools/run_with_bazel.sh test //test/...
