name: Commit

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vagrant:
    runs-on: macos-10.15

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant

      - name: Install packages
        run: |
          brew install coreutils

      - name: Install ansible and its plugins
        run: |
          sudo pip3 install --upgrade pip
          sudo pip3 install ansible-core

      - name: Install ansible plugins
        run: |
          ansible-galaxy collection install ansible.posix
          ansible-galaxy collection install kubernetes.core

      - name: Dump vagrant verson
        run: vagrant --version

      - name: Start machines
        run: |
          vagrant up

      - name: Verify network
        run: |
          vagrant ssh vm1 -c 'ping -c 1 8.8.8.8'
          vagrant ssh vm2 -c 'ping -c 1 8.8.8.8'
          vagrant ssh vm1 -c 'ping -c 1 192.168.0.2'
          vagrant ssh vm2 -c 'ping -c 1 192.168.0.1'

      - name: Show VM info
        run: |
          VBoxManage list vms -l

      - name: Show kube config
        run: |
          vagrant ssh vm1 -c 'kubectl get nodes'
          vagrant ssh vm1 -c 'kubectl get deployments --all-namespaces'
          vagrant ssh vm1 -c 'kubectl get services --all-namespaces'
          vagrant ssh vm1 -c 'kubectl get pods --all-namespaces'

      - name: Fetch console log of node 1
        run: cat /tmp/vm1.log

      - name: Fetch console log of node 2
        run: cat /tmp/vm2.log

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Add docker gpg key
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      - name: Add docker repository
        run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

      - name: Install docker
        run: |
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Update our repository
        run: |
          ./tools/run_with_bazel.sh gazelle
          ./tools/run_with_bazel.sh update-repos

      - name: Reload our repository
        run: |
          ./tools/run_with_bazel.sh gazelle

      - name: Do selftest
        run: ./tools/run_with_bazel.sh test //test/...
