name: Commit

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update APT repository
        run: sudo apt update -y

      - name: Install docker
        run: sudo apt install -y docker.io

      - name: Update our repository
        run: |
          ./tools/run_with_bazel.sh gazelle
          ./tools/run_with_bazel.sh update-repos

      - name: Reload our repository
        run: |
          ./tools/run_with_bazel.sh gazelle

      - name: Do selftest
        run: ./tools/run_with_bazel.sh test //test/...

      - name: Build commands
        run: ./tools/run_with_bazel.sh build //cmds/...
