name: Commit

on:
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vagrant:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Dump vagrant verson
        run: vagrant --version

      - name: Start machines
        run: |
          vagrant up
          vagrant status

      - name: Verify network
        run: |
          vagrant ssh vm1 -c 'ping -c 10 8.8.8.8'
          vagrant ssh vm2 -c 'ping -c 10 8.8.8.8'
          vagrant ssh vm1 -c 'ping -c 10 192.168.0.2'
          vagrant ssh vm2 -c 'ping -c 10 192.168.0.1'

      - name: Show VM info
        run: |
          VBoxManage showvminfo $(VBoxManage list runningvms | head -n 1)

      - name: Install drbd
        run: |
          vagrant ssh vm1 -c 'sudo apt update'
          vagrant ssh vm1 -c 'sudo apt search drbd'

      - name: Fetch console log of node 1
        run:
          cat /tmp/vm1.log

      - name: Fetch console log of node 2
        run:
          cat /tmp/vm2.log

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Add docker gpg key
        run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      - name: Add docker repository
        run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

      - name: Add bazel gpg key
        run: curl -fsSL https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -

      - name: Add bazel repository
        run: echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

      - name: Install docker
        run: |
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Update our repository
        run: |
          ./tools/run_with_bazel.sh gazelle
          ./tools/run_with_bazel.sh update-repos

      - name: Reload our repository
        run: |
          ./tools/run_with_bazel.sh gazelle

      - name: Do selftest
        run: ./tools/run_with_bazel.sh test //test/...
